package com.agentx.core.workflow;

import com.agentx.api.workflow.WorkflowContext;
import java.util.Map;
import java.util.UUID;

/**
 * Represents a single executable step within a workflow.
 */
@FunctionalInterface
public interface WorkflowStep {

    /**
     * Unique identifier for the step. Defaults to a random UUID.
     *
     * @return step ID
     */
    default String id() {
        return UUID.randomUUID().toString();
    }

    /**
     * Executes the step using the workflow context.
     *
     * @param context the workflow execution context
     * @return output generated by this step
     */
    Map<String, Object> execute(WorkflowContext context);
}
